
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  {{- template "chart.metadata" . -}}
spec:
  host: {{ .Release.Name }}.ticc.svc.cluster.local
  subsets:
    - name: v1
      labels:
        version: v1

