
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  {{- template "chart.metadata" . -}}
spec:
  hosts:
  - "*"
  gateways:
  - avid-gateway
  http:
  - name: {{ .Release.Name }}-routes
    match:
    {{- range .Values.uris }}
      - uri:
          prefix: {{ . }}
    {{- end}}
    # timeout: {{ .Values.timeout | default "2s" }}
    route:
    - destination:
        host: {{ .Release.Name }}.avid.svc.cluster.local
        subset: v1
    retries:
      attempts: 3
      perTryTimeout: {{ .Values.timeout | default "2s" }}
    corsPolicy:
      allowMethods:
        - POST
        - OPTIONS
      allowOrigins:
      - regex: ^http://localhost:[\d]+$
      - regex: ^https://[\w-.]*avidaml.com$
      allowHeaders:
      - authorization
      - content-type
      - x-grpc-web
      - grpc-timeout
      - x-accept-response-streaming
      - x-user-agent
      - x-feature-flag
      exposeHeaders:
      - grpc-status
      - grpc-message
      allowCredentials: true
      maxAge: "24h"