---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: agent-ingest-management-nodescope
  namespace: kube-system
  labels:
    app: agent-ingest-management-nodescope
    group: ingest-management
spec:
  selector:
    matchLabels:
      app: agent-ingest-management-nodescope
  template:
    metadata:
      labels:
        app: agent-ingest-management-nodescope
        group: ingest-management
    spec:
      serviceAccountName: agent-ingest-management
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: agent-ingest-management-nodescope
          image: docker.elastic.co/beats/elastic-agent:7.10.1
          env:
            - name: FLEET_ENROLL
              value: "1"
            - name: FLEET_ENROLLMENT_TOKEN
              value: "Q1FMRl9uWUJUOXpNZFVjSndhbmI6Sy1QaU5KRmlRMDJxcVJJa0lXMFFNZw=="
            - name: KIBANA_HOST
              value: "https://5d8d33f6956a4030b3d795d42c350b75.australiaeast.azure.elastic-cloud.com:9243"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            runAsUser: 0
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-ingest-management-config-nodescope
  namespace: kube-system
  labels:
    group: ingest-management
data:
  elastic-agent.yml: |-
    management:
      mode: "fleet"
    grpc:
      # listen address for the GRPC server that spawned processes connect back to.
      address: localhost
      # port for the GRPC server that spawned processes connect back to.
      port: 6788
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: agent-ingest-management
subjects:
  - kind: ServiceAccount
    name: agent-ingest-management
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: agent-ingest-management
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agent-ingest-management
  labels:
    k8s-app: agent-ingest-management
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - namespaces
      - events
      - pods
      - secrets
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions"]
    resources:
      - replicasets
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources:
      - statefulsets
      - deployments
      - replicasets
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - ""
    resources:
      - nodes/stats
    verbs:
      - get
  # required for apiserver
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - get
---