{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "es-agent.serviceAccountName" . }}
  namespace: kube-system
  labels:
    k8s-app: {{ include "es-agent.serviceAccountName" . }}
    {{- include "es-agent.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}