
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- template "chart.metadata" . -}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      version: {{ .Chart.AppVersion }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        version: {{ .Chart.AppVersion }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }} # trick to trigger rollout restart
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "avidhub.azurecr.io/{{ .Release.Name }}:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.port }}
          envFrom:
          {{- range .Values.deployment.secrets }}
            - secretRef:
                name: {{ . }}
          {{- end }}
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
      nodeSelector:
        "beta.kubernetes.io/os": linux
